name: Deploy to Remote Server
on:
  push:
    branches:
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.REMOTE_SSH_KEY }}

      - name: Add remote host to known_hosts

        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.131.153.251 >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.131.153.251 << 'EOF'
            cd docker-odoo-binaural
            echo "[+] Pulling latest code from GitHub..."
            git pull
            echo "[+] Restarting Docker container..."
            ./odoo restart
            echo "[+] Deployment completed successfully."
          2>&1 | tee -a /var/log/deploy.log
          EOF